# Generated by Django 5.1.3 on 2025-01-26 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Маленький'), ('medium', 'Середній'), ('high', 'Великий')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('to_do', 'Зробити'), ('in_progress', 'В процесі'), ('done', 'Готово')], default='to_do', max_length=20)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('executers', models.ManyToManyField(blank=True, null=True, related_name='appointed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
