# Generated by Django 5.1.3 on 2025-01-27 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executers',
            field=models.ManyToManyField(blank=True, related_name='appointed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
