# Generated by Django 5.1.3 on 2025-01-31 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_executers_executer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executer',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executers', to='todo.task'),
        ),
    ]
